import MapKit
import os
import simd

/// A type that can be clustered on a map based on its geographic location.
///
/// Conform your custom types to `Clusterable` to enable clustering with ``ClusterManager``.
/// The clustering algorithm groups items based on their proximity to each other.
///
/// ## Example
/// ```swift
/// struct City: Clusterable {
///     let coordinate: CLLocationCoordinate2D
///     let name: String
/// }
/// ```
///
/// - Important: Types conforming to `Clusterable` must also conform to ``Equatable`` and `Sendable`
///   for safe concurrent clustering operations.
public protocol Clusterable: Equatable, Sendable {
    /// The geographic coordinate of the clusterable item.
    ///
    /// This coordinate is used by the clustering algorithm to determine proximity between items.
    var coordinate: CLLocationCoordinate2D { get }
}

/// A collection of geographically proximate items on a map.
///
/// A cluster groups one or more ``Clusterable`` items that are close to each other,
/// calculating a center point based on the average coordinates of all items.
///
/// Clusters are automatically generated by ``ClusterManager`` using the DBSCAN algorithm
/// and provide a convenient way to visualize grouped data on maps.
///
/// ## Example
/// ```swift
/// // Clusters are created by ClusterManager during an update call.
/// for cluster in clusterManager.clusters {
///     print(cluster.size)    // number of items in this cluster
///     print(cluster.center)  // average coordinate of the items
/// }
/// ```
///
/// ## Topics
///
/// ### Accessing Cluster Properties
/// - ``id``
/// - ``items``
/// - ``center``
/// - ``size``
public struct Cluster<CR: Clusterable>: Identifiable, Sendable {
    /// Unique identifier for the cluster.
    ///
    /// Each cluster receives a unique UUID when created, ensuring stable identity
    /// for SwiftUI animations and state management.
    public let id: UUID = .init()

    /// The items contained within this cluster.
    ///
    /// All items in the cluster are within the clustering distance threshold (epsilon)
    /// as determined by the DBSCAN algorithm.
    public let items: [CR]

    /// The geographic center point of the cluster.
    ///
    /// Calculated as the centroid (average latitude and longitude) of all items.
    public let center: CLLocationCoordinate2D

    /// The number of items in the cluster.
    ///
    /// This is a convenience property equivalent to `items.count`.
    public var size: Int { items.count }

    /// Creates a new cluster containing the specified items.
    ///
    /// The cluster's center point is automatically calculated as the centroid
    /// (average coordinate) of all items.
    ///
    /// - Parameter items: The clusterable items to group together.
    init(items: [CR]) {
        self.items = items

        let count = Double(items.count)
        center = items.lazy
            .reduce(CLLocationCoordinate2D(latitude: 0, longitude: 0)) { result, item in
                CLLocationCoordinate2D(
                    latitude: result.latitude + item.coordinate.latitude / count,
                    longitude: result.longitude + item.coordinate.longitude / count
                )
            }
    }
}

extension Cluster: Hashable {
    public static func == (lhs: Cluster, rhs: Cluster) -> Bool {
        lhs.id == rhs.id
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
}

/// Manages the clustering of map annotations using the DBSCAN algorithm.
///
/// `ClusterManager` efficiently groups ``Clusterable`` items based on their geographic proximity,
/// using the DBSCAN (Density-Based Spatial Clustering of Applications with Noise) algorithm
/// with KD-tree spatial indexing for O(n log n) performance.
///
/// The manager is designed to work seamlessly with SwiftUI's `@Observable` macro, automatically
/// triggering view updates when clusters change.
///
/// ## Example Usage
/// ```swift
/// struct MapView: View {
///     @State private var manager = ClusterManager<MapPin>()
///     @State private var pins: [MapPin] = []
///
///     var body: some View {
///         Map {
///             ForEach(manager.clusters) { cluster in
///                 if cluster.size == 1 {
///                     Annotation(cluster.items[0].title, coordinate: cluster.center) {
///                         Image(systemName: "mappin")
///                     }
///                 } else {
///                     Annotation("\(cluster.size)", coordinate: cluster.center) {
///                         Circle()
///                             .fill(.blue)
///                             .frame(width: 40, height: 40)
///                     }
///                 }
///             }
///         }
///         .onMapCameraChange { context in
///             if let epsilon = mapProxy.degrees(fromPixels: 50) {
///                 await manager.update(pins, epsilon: epsilon)
///             }
///         }
///     }
/// }
/// ```
///
/// ## Topics
///
/// ### Creating a Cluster Manager
/// - ``init()``
///
/// ### Managing Clusters
/// - ``update(_:epsilon:minimumPoints:)``
/// - ``clusters``
/// - ``outliers``
///
/// ### Performance
/// - Clustering complexity: O(n log n) with KD-tree spatial indexing
/// - Space complexity: O(n)
/// - Runs clustering on background threads to avoid blocking the UI
@Observable
public class ClusterManager<CR: Clusterable> {
    // MARK: - Type Aliases
    
    /// A 2D point in coordinate space (latitude, longitude)
    private typealias Point = SIMD2<Double>
    
    /// A collection of points representing a raw cluster from DBSCAN
    private typealias PointCluster = [Point]
    
    /// A collection of array indices representing items in a cluster
    private typealias IndexCluster = [Int]
    
    /// Maps quantized coordinates to the original item indices
    private typealias CoordinateIndexMap = [PointKey: [Int]]
    
    // MARK: - Private Properties

    private static var logger: Logger {
        Logger(subsystem: "Clusterables", category: "ClusterManager")
    }
    
    // MARK: - Public Properties
    
    /// The current set of clusters generated from the most recent update.
    ///
    /// This property is observed by SwiftUI, triggering view updates when clusters change.
    /// Initially empty until ``update(_:epsilon:minimumPoints:)`` is called.
    ///
    /// Items that don't meet the density threshold are excluded from clusters
    /// and placed in ``outliers`` instead.
    public private(set) var clusters: [Cluster<CR>]
    
    /// Items that were not assigned to any cluster in the most recent update.
    ///
    /// Outliers are points that don't have enough neighbors within ``update(_:epsilon:minimumPoints:)``'s
    /// `epsilon` distance to meet the `minimumPoints` threshold. With the default
    /// `minimumPoints` of `1`, this array is always empty since every point forms
    /// at least a single-item cluster.
    ///
    /// Use outliers to render unclustered items differently on the map, or to identify
    /// isolated data points.
    public private(set) var outliers: [CR]

    // MARK: - Initialization
    
    /// Creates a new cluster manager with an empty set of clusters.
    ///
    /// After initialization, call ``update(_:epsilon:minimumPoints:)`` to generate clusters
    /// from your data.
    public init() {
        clusters = []
        outliers = []
    }

    // MARK: - Public Methods
    
    /// Updates the clusters based on the desired clustering distance and density threshold.
    ///
    /// This method analyzes the provided items and groups them into clusters based on their
    /// geographic proximity. Items closer than `epsilon` degrees are grouped together,
    /// provided they meet the `minimumPoints` density threshold. Items that don't meet
    /// the threshold are placed in ``outliers``.
    ///
    /// The clustering operation runs asynchronously on a background thread and updates
    /// the ``clusters`` and ``outliers`` properties on the main actor when complete.
    ///
    /// - Parameters:
    ///   - items: The items to cluster. Each item must conform to ``Clusterable``.
    ///   - epsilon: The maximum distance in degrees between two points for them to be
    ///     considered neighbors. Must be positive and finite. Use
    ///     ``MapProxy/degrees(fromPixels:)`` to convert screen-space pixel spacing to
    ///     degrees at the current zoom level. If the value is invalid (zero, negative,
    ///     NaN, or infinite), the call is ignored and the existing clusters are preserved.
    ///   - minimumPoints: The minimum number of neighbors required for a point to be
    ///     considered a core point. Must be non-negative. Points with fewer neighbors
    ///     become outliers. Defaults to `1`, meaning every point belongs to a cluster.
    ///     If the value is negative, the call is ignored and the existing clusters
    ///     are preserved.
    ///
    /// - Note: This method should typically be called in response to map camera changes
    ///   using SwiftUI's `.onMapCameraChange` modifier.
    ///
    /// Calling this method while a previous update is still in progress
    /// discards the earlier results. Only the most recent update's results
    /// are applied.
    ///
    /// ## Example
    /// ```swift
    /// MapReader { mapProxy in
    ///     Map {
    ///         // Map content
    ///     }
    ///     .onMapCameraChange { context in
    ///         if let epsilon = mapProxy.degrees(fromPixels: 50) {
    ///             await clusterManager.update(pins, epsilon: epsilon)
    ///         }
    ///     }
    /// }
    /// ```
    public func update(_ items: [CR], epsilon: Double, minimumPoints: Int = 1) async {
        guard epsilon > 0 && epsilon.isFinite else {
            Self.logger.warning("update ignored: epsilon must be positive and finite, got \(epsilon)")
            return
        }
        guard minimumPoints >= 0 else {
            Self.logger.warning("update ignored: minimumPoints must be non-negative, got \(minimumPoints)")
            return
        }

        let generation = _generation.withLock { value -> Int in
            value += 1
            return value
        }

        let (newClusters, newOutliers) = await Self.makeClusters(
            items, epsilon: epsilon, minimumPoints: minimumPoints,
            generation: generation, currentGeneration: _generation
        )

        // Only apply results if no newer update has started
        guard _generation.withLock({ $0 }) == generation else {
            Self.logger.debug("update generation \(generation) discarded: a newer update is in progress")
            return
        }
        await setResults(newClusters, newOutliers)
    }
    
    @MainActor
    private func setResults(_ newClusters: [Cluster<CR>], _ newOutliers: [CR]) {
        clusters = newClusters
        outliers = newOutliers
    }

    // MARK: - Private Types
    
    fileprivate struct PointKey: Hashable, Sendable {
        let latKey: Int64
        let lonKey: Int64
    }
    
    // MARK: - Private Properties
    
    /// The precision used for coordinate hashing (6 decimal places ≈ 0.1 meter accuracy)
    private static var coordinatePrecision: Double { 1_000_000.0 }
    
    /// Incremented on each ``update(_:epsilon:minimumPoints:)`` call to detect and discard stale results.
    private let _generation = OSAllocatedUnfairLock(initialState: 0)

    // MARK: - Private Methods
    
    /// Quantizes a latitude/longitude pair into a ``PointKey`` for dictionary lookup.
    ///
    /// This is extracted into a single function because the same quantization must be
    /// applied in both ``preprocessItems(_:)`` (when building the coordinate-to-index map)
    /// and ``remapPointsToIndices(_:coordIndexMap:)`` (when looking up indices after DBSCAN).
    /// Duplicating the arithmetic in two places risks a silent mismatch if one is changed
    /// without the other, causing lookups to return nil and clusters to come out empty.
    private static func pointKey(latitude: Double, longitude: Double) -> PointKey {
        PointKey(
            latKey: Int64((latitude * coordinatePrecision).rounded()),
            lonKey: Int64((longitude * coordinatePrecision).rounded())
        )
    }
    
    /// Converts clusterable items into SIMD points and builds a reverse lookup map.
    ///
    /// This preprocessing step quantizes coordinates for efficient hashing and creates
    /// a bidirectional mapping between SIMD points and original item indices.
    ///
    /// - Parameter items: The items to convert.
    /// - Returns: A tuple containing:
    ///   - `points`: Array of SIMD2 points for DBSCAN input.
    ///   - `coordIndexMap`: Dictionary mapping quantized coordinates to original item indices.
    private static func preprocessItems(_ items: [CR]) -> (points: [Point], coordIndexMap: CoordinateIndexMap) {
        var points: [Point] = []
        points.reserveCapacity(items.count)
        var coordIndexMap: CoordinateIndexMap = [:]
        coordIndexMap.reserveCapacity(items.count)
        
        for (i, item) in items.enumerated() {
            let lat = item.coordinate.latitude
            let lon = item.coordinate.longitude
            points.append(Point(lat, lon))
            
            let key = pointKey(latitude: lat, longitude: lon)
            coordIndexMap[key, default: []].append(i)
        }
        
        return (points, coordIndexMap)
    }
    
    /// Remaps SIMD2 points back to original item indices using the coordinate map.
    ///
    /// After DBSCAN produces clusters of SIMD2 points, this method translates them back
    /// to indices of the original items using the quantized coordinate hash map.
    ///
    /// - Parameters:
    ///   - rawClusters: Clusters of SIMD2 points output from DBSCAN.
    ///   - coordIndexMap: Dictionary mapping quantized coordinates to item indices.
    /// - Returns: Array of index arrays, where each inner array represents a cluster's item indices.
    private static func remapPointsToIndices(
        _ rawClusters: [PointCluster],
        coordIndexMap: CoordinateIndexMap
    ) -> [IndexCluster] {
        var indexClusters: [IndexCluster] = []
        indexClusters.reserveCapacity(rawClusters.count)
        
        for raw in rawClusters {
            guard !raw.isEmpty else { continue }
            var clusterIndices: IndexCluster = []
            clusterIndices.reserveCapacity(raw.count)
            
            for pt in raw {
                // SIMD2 stores (lat, lon) as (x, y)
                let key = pointKey(latitude: pt.x, longitude: pt.y)
                if let indices = coordIndexMap[key] {
                    clusterIndices.append(contentsOf: indices)
                }
            }
            
            if !clusterIndices.isEmpty {
                indexClusters.append(clusterIndices)
            }
        }
        
        return indexClusters
    }
    
    /// Creates clusters from items using the DBSCAN algorithm.
    ///
    /// This is the main clustering implementation that:
    /// 1. Preprocesses items into SIMD2 points
    /// 2. Runs DBSCAN clustering on a background thread
    /// 3. Remaps results back to original items
    /// 4. Constructs ``Cluster`` objects and collects outliers
    ///
    /// - Parameters:
    ///   - items: The items to cluster.
    ///   - epsilon: The maximum distance (in degrees) between two items for them to be
    ///     considered part of the same cluster.
    ///   - minimumPoints: The minimum number of neighbors required for a core point.
    ///   - generation: The generation number for this update call, used to detect staleness.
    ///   - currentGeneration: Lock holding the current generation counter, passed through
    ///     to ``DBSCANClusterer`` so DBSCAN can bail out mid-computation when a newer
    ///     update has started.
    /// - Returns: A tuple of ``Cluster`` objects and outlier items. Returns empty arrays
    ///   if a newer update started before this one completed.
    ///
    /// - Complexity:
    ///   - Time: O(n log n) with KD-tree spatial indexing
    ///   - Space: O(n) for storing points, indices, and clusters
    private static func makeClusters(
        _ items: [CR], epsilon: Double, minimumPoints: Int,
        generation: Int, currentGeneration: OSAllocatedUnfairLock<Int>
    ) async -> (clusters: [Cluster<CR>], outliers: [CR]) {

        guard !items.isEmpty else {
            return ([], [])
        }

        // Step 1: Preprocess items into SIMD points and build coordinate mapping
        let (points, coordIndexMap) = preprocessItems(items)

        // Bail out if a newer update has started before entering detached task
        guard currentGeneration.withLock({ $0 }) == generation else {
            logger.debug("makeClusters generation \(generation) cancelled before DBSCAN")
            return ([], [])
        }

        // Step 2: Run DBSCAN clustering in a detached task
        let (rawIndexClusters, outlierIndices): ([IndexCluster], IndexCluster) = await Task.detached { [points, coordIndexMap, epsilon, minimumPoints, currentGeneration] () -> ([IndexCluster], IndexCluster) in

            let clusterer = DBSCANClusterer(values: points)
            let rawClusters: [[SIMD2<Double>]]
            let rawOutliers: [SIMD2<Double>]
            do {
                (rawClusters, rawOutliers) = try clusterer.cluster(
                    epsilon: epsilon, minimumPoints: minimumPoints,
                    generation: generation, currentGeneration: currentGeneration
                )
            } catch {
                logger.error("DBSCANClusterer.cluster threw unexpectedly: \(error)")
                assertionFailure("DBSCANClusterer.cluster threw unexpectedly: \(error)")
                return ([], [])
            }
            
            // Step 3: Remap SIMD points back to original indices
            let clusterIndices = remapPointsToIndices(rawClusters, coordIndexMap: coordIndexMap)
            let outlierIndices = remapPointsToIndices([rawOutliers], coordIndexMap: coordIndexMap).flatMap { $0 }
            return (clusterIndices, outlierIndices)
        }.value

        // Bail out before constructing Cluster objects
        guard currentGeneration.withLock({ $0 }) == generation else {
            logger.debug("makeClusters generation \(generation) cancelled after DBSCAN")
            return ([], [])
        }

        // Step 4: Convert index clusters to Cluster<CR> objects
        let clusters = rawIndexClusters.compactMap { indices -> Cluster<CR>? in
            guard !indices.isEmpty else { return nil }
            let clusterItems = indices.map { items[$0] }
            return Cluster(items: clusterItems)
        }
        
        let outliers = outlierIndices.map { items[$0] }
        
        return (clusters, outliers)
    }
}
