import KDTree
import MapKit
import SwiftUI
import simd

/// A type that can be clustered on a map based on its geographic location.
///
/// Conform your custom types to `Clusterable` to enable clustering with ``ClusterManager``.
/// The clustering algorithm groups items based on their proximity to each other.
///
/// ## Example
/// ```swift
/// struct City: Clusterable {
///     let coordinate: CLLocationCoordinate2D
///     let name: String
///
///     static func == (lhs: City, rhs: City) -> Bool {
///         lhs.name == rhs.name
///     }
/// }
/// ```
///
/// - Important: Types conforming to `Clusterable` must also conform to ``Equatable`` and `Sendable`
///   for safe concurrent clustering operations.
public protocol Clusterable: Equatable, Sendable {
    /// The geographic coordinate of the clusterable item.
    ///
    /// This coordinate is used by the clustering algorithm to determine proximity between items.
    var coordinate: CLLocationCoordinate2D { get }
}

/// A protocol for views that provide cluster management functionality.
///
/// Conform your SwiftUI views to this protocol to standardize cluster manager access patterns.
///
/// ## Example
/// ```swift
/// struct MapView: View, ClusterManagerProvider {
///     @State private var clusterManager = ClusterManager<MapPin>()
///
///     var body: some View {
///         Map {
///             ForEach(clusterManager.clusters) { cluster in
///                 // Render cluster annotations
///             }
///         }
///     }
/// }
/// ```
public protocol ClusterManagerProvider: View {
    /// The type of items that can be clustered.
    associatedtype ClusterableType: Clusterable

    /// The cluster manager instance responsible for managing clusters.
    var clusterManager: ClusterManager<ClusterableType> { get }
}

/// A collection of geographically proximate items on a map.
///
/// A cluster groups one or more ``Clusterable`` items that are close to each other,
/// calculating a center point based on the average coordinates of all items.
///
/// Clusters are automatically generated by ``ClusterManager`` using the DBSCAN algorithm
/// and provide a convenient way to visualize grouped data on maps.
///
/// ## Example
/// ```swift
/// let cluster = Cluster(items: [pin1, pin2, pin3])
/// print(cluster.size)    // 3
/// print(cluster.center)  // CLLocationCoordinate2D(...)
/// ```
///
/// ## Topics
///
/// ### Creating Clusters
/// - ``init(items:)``
///
/// ### Accessing Cluster Properties
/// - ``id``
/// - ``items``
/// - ``center``
/// - ``size``
public struct Cluster<CR: Clusterable>: Identifiable, Sendable {
    /// Unique identifier for the cluster.
    ///
    /// Each cluster receives a unique UUID when created, ensuring stable identity
    /// for SwiftUI animations and state management.
    public let id: UUID = .init()

    /// The items contained within this cluster.
    ///
    /// All items in the cluster are within the clustering distance threshold (epsilon)
    /// as determined by the DBSCAN algorithm.
    public let items: [CR]

    /// The geographic center point of the cluster.
    ///
    /// Calculated as the centroid (average latitude and longitude) of all items.
    public let center: CLLocationCoordinate2D

    /// The number of items in the cluster.
    ///
    /// This is a convenience property equivalent to `items.count`.
    public var size: Int { items.count }

    /// Creates a new cluster containing the specified items.
    ///
    /// The cluster's center point is automatically calculated as the centroid
    /// (average coordinate) of all items.
    ///
    /// - Parameter items: The clusterable items to group together. Must not be empty.
    ///
    /// - Note: This initializer is typically called by ``ClusterManager`` rather than
    ///   directly in application code.
    public init(items: [CR]) {
        self.items = items

        let count = Double(items.count)
        center = items.lazy
            .reduce(CLLocationCoordinate2D(latitude: 0, longitude: 0)) { result, item in
                CLLocationCoordinate2D(
                    latitude: result.latitude + item.coordinate.latitude / count,
                    longitude: result.longitude + item.coordinate.longitude / count
                )
            }
    }
}

extension Cluster: Hashable {
    public static func == (lhs: Cluster, rhs: Cluster) -> Bool {
        lhs.center == rhs.center && lhs.size == rhs.size
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(center)
        hasher.combine(size)
    }
}

/// Manages the clustering of map annotations using the DBSCAN algorithm.
///
/// `ClusterManager` efficiently groups ``Clusterable`` items based on their geographic proximity,
/// using the DBSCAN (Density-Based Spatial Clustering of Applications with Noise) algorithm
/// with KD-tree spatial indexing for O(n log n) performance.
///
/// The manager is designed to work seamlessly with SwiftUI's `@Observable` macro, automatically
/// triggering view updates when clusters change.
///
/// ## Example Usage
/// ```swift
/// struct MapView: View {
///     @State private var manager = ClusterManager<MapPin>()
///     @State private var pins: [MapPin] = []
///
///     var body: some View {
///         Map {
///             ForEach(manager.clusters) { cluster in
///                 if cluster.size == 1 {
///                     Annotation(cluster.items[0].title, coordinate: cluster.center) {
///                         Image(systemName: "mappin")
///                     }
///                 } else {
///                     Annotation("\(cluster.size)", coordinate: cluster.center) {
///                         Circle()
///                             .fill(.blue)
///                             .frame(width: 40, height: 40)
///                     }
///                 }
///             }
///         }
///         .onMapCameraChange { context in
///             await manager.update(pins, mapProxy: context.proxy, spacing: 50)
///         }
///     }
/// }
/// ```
///
/// ## Topics
///
/// ### Creating a Cluster Manager
/// - ``init()``
///
/// ### Managing Clusters
/// - ``update(_:mapProxy:spacing:)``
/// - ``clusters``
///
/// ### Performance
/// - Clustering complexity: O(n log n) with KD-tree spatial indexing
/// - Space complexity: O(n)
/// - Runs clustering on background threads to avoid blocking the UI
@Observable
public class ClusterManager<CR: Clusterable> {
    // MARK: - Type Aliases
    
    /// A 2D point in coordinate space (latitude, longitude)
    private typealias Point = SIMD2<Double>
    
    /// A collection of points representing a raw cluster from DBSCAN
    private typealias PointCluster = [Point]
    
    /// A collection of array indices representing items in a cluster
    private typealias IndexCluster = [Int]
    
    /// Maps quantized coordinates to the original item indices
    private typealias CoordinateIndexMap = [PointKey: [Int]]
    
    // MARK: - Public Properties
    
    /// The current set of clusters generated from the most recent update.
    ///
    /// This property is observed by SwiftUI, triggering view updates when clusters change.
    /// Initially empty until ``update(_:mapProxy:spacing:)`` is called.
    public private(set) var clusters: [Cluster<CR>]

    // MARK: - Initialization
    
    /// Creates a new cluster manager with an empty set of clusters.
    ///
    /// After initialization, call ``update(_:mapProxy:spacing:)`` to generate clusters
    /// from your data.
    public init() {
        clusters = []
    }

    // MARK: - Public Methods
    
    /// Updates the clusters based on the current map view state and desired cluster spacing.
    ///
    /// This method analyzes the provided items and groups them into clusters based on their
    /// visual proximity in the current map view. Items closer than `spacing` screen points
    /// are grouped together.
    ///
    /// The clustering operation runs asynchronously on a background thread and updates
    /// the ``clusters`` property on the main actor when complete.
    ///
    /// - Parameters:
    ///   - items: The items to cluster. Each item must conform to ``Clusterable``.
    ///   - mapProxy: The map proxy from SwiftUI's `Map` view, used to convert between
    ///     screen coordinates and geographic coordinates.
    ///   - spacing: The minimum spacing between clusters in screen points (pixels).
    ///     Items closer than this distance will be grouped into the same cluster.
    ///
    /// - Note: This method should typically be called in response to map camera changes
    ///   using SwiftUI's `.onMapCameraChange` modifier.
    ///
    /// ## Example
    /// ```swift
    /// Map {
    ///     // Map content
    /// }
    /// .onMapCameraChange { context in
    ///     await clusterManager.update(pins, mapProxy: context.proxy, spacing: 50)
    /// }
    /// ```
    @MainActor
    public func update(_ items: [CR], mapProxy: MapProxy, spacing: Int) async {
        guard let distance = mapProxy.degrees(fromPixels: spacing) else { return }
        let newClusters = await Self.makeClusters(items, epsilon: distance)
        clusters = newClusters
    }

    // MARK: - Private Types
    
    fileprivate struct PointKey: Hashable, Sendable {
        let latKey: Int64
        let lonKey: Int64
    }
    
    // MARK: - Private Properties
    
    /// The precision used for coordinate hashing (6 decimal places ≈ 0.1 meter accuracy)
    private static var coordinatePrecision: Double { 1_000_000.0 }

    // MARK: - Private Methods
    
    /// Converts clusterable items into SIMD points and builds a reverse lookup map.
    ///
    /// This preprocessing step quantizes coordinates for efficient hashing and creates
    /// a bidirectional mapping between SIMD points and original item indices.
    ///
    /// - Parameter items: The items to convert.
    /// - Returns: A tuple containing:
    ///   - `points`: Array of SIMD2 points for DBSCAN input.
    ///   - `coordIndexMap`: Dictionary mapping quantized coordinates to original item indices.
    private static func preprocessItems(_ items: [CR]) -> (points: [Point], coordIndexMap: CoordinateIndexMap) {
        var points: [Point] = []
        points.reserveCapacity(items.count)
        var coordIndexMap: CoordinateIndexMap = [:]
        coordIndexMap.reserveCapacity(items.count * 2)
        
        for (i, item) in items.enumerated() {
            let lat = item.coordinate.latitude
            let lon = item.coordinate.longitude
            points.append(Point(lat, lon))
            
            let latKey = Int64((lat * coordinatePrecision).rounded())
            let lonKey = Int64((lon * coordinatePrecision).rounded())
            let key = PointKey(latKey: latKey, lonKey: lonKey)
            coordIndexMap[key, default: []].append(i)
        }
        
        return (points, coordIndexMap)
    }
    
    /// Remaps SIMD2 points back to original item indices using the coordinate map.
    ///
    /// After DBSCAN produces clusters of SIMD2 points, this method translates them back
    /// to indices of the original items using the quantized coordinate hash map.
    ///
    /// - Parameters:
    ///   - rawClusters: Clusters of SIMD2 points output from DBSCAN.
    ///   - coordIndexMap: Dictionary mapping quantized coordinates to item indices.
    /// - Returns: Array of index arrays, where each inner array represents a cluster's item indices.
    private static func remapPointsToIndices(
        _ rawClusters: [PointCluster],
        coordIndexMap: CoordinateIndexMap
    ) -> [IndexCluster] {
        var indexClusters: [IndexCluster] = []
        indexClusters.reserveCapacity(rawClusters.count)
        
        for raw in rawClusters {
            guard !raw.isEmpty else { continue }
            var clusterIndices: IndexCluster = []
            clusterIndices.reserveCapacity(raw.count)
            
            for pt in raw {
                // Note: SIMD2 stores (lat, lon) as (x, y)
                let latKey = Int64((pt.x * coordinatePrecision).rounded())
                let lonKey = Int64((pt.y * coordinatePrecision).rounded())
                let key = PointKey(latKey: latKey, lonKey: lonKey)
                
                if let indices = coordIndexMap[key] {
                    clusterIndices.append(contentsOf: indices)
                }
            }
            
            if !clusterIndices.isEmpty {
                indexClusters.append(clusterIndices)
            }
        }
        
        return indexClusters
    }
    
    /// Creates clusters from items using the DBSCAN algorithm.
    ///
    /// This is the main clustering implementation that:
    /// 1. Preprocesses items into SIMD2 points
    /// 2. Runs DBSCAN clustering on a background thread
    /// 3. Remaps results back to original items
    /// 4. Constructs ``Cluster`` objects
    ///
    /// - Parameters:
    ///   - items: The items to cluster.
    ///   - epsilon: The maximum distance (in degrees) between two items for them to be
    ///     considered part of the same cluster.
    /// - Returns: An array of ``Cluster`` objects.
    ///
    /// - Complexity:
    ///   - Time: O(n log n) with KD-tree spatial indexing
    ///   - Space: O(n) for storing points, indices, and clusters
    private static func makeClusters(_ items: [CR], epsilon: Double) async -> [Cluster<CR>] {

        guard !items.isEmpty else {
            return []
        }

        // Step 1: Preprocess items into SIMD points and build coordinate mapping
        let (points, coordIndexMap) = preprocessItems(items)

        // Step 2: Run DBSCAN clustering in a detached task
        let rawIndexClusters: [IndexCluster] = await Task.detached { [points, coordIndexMap, epsilon] () -> [IndexCluster] in

            let clusterer = DBSCANClusterer(values: points)
            let (rawClusters, _) = clusterer.cluster(epsilon: epsilon, minimumPoints: 1)
            
            // Step 3: Remap SIMD points back to original indices
            return remapPointsToIndices(rawClusters, coordIndexMap: coordIndexMap)
        }.value

        // Step 4: Convert index clusters to Cluster<CR> objects
        return rawIndexClusters.compactMap { indices -> Cluster<CR>? in
            guard !indices.isEmpty else { return nil }
            let clusterItems = indices.map { items[$0] }
            return Cluster(items: clusterItems)
        }
    }
}
